version: 3

tasks:
  tailwind-gen:
    dir: ./src/Dakoq.WebApp/Dakoq.WebApp
    cmds:
      - npx @tailwindcss/cli -i "./Styles/app.css" -o "./wwwroot/css/app.css"

  tailwind-watch:
    dir: ./src/Dakoq.WebApp/Dakoq.WebApp
    cmds:
      - npx @tailwindcss/cli -i "./Styles/app.css" -o "./wwwroot/css/app.css" --watch

  dev-up:
    cmds:
      - task: tailwind-gen
      - docker compose up -d --build

  dev-down:
    cmds:
      - docker compose down

  dev-restart:
    cmds:
      - task: tailwind-gen
      - docker compose build
      - docker compose down
      - docker compose up -d
