version: 3

tasks:
  install-libs:
    cmds:
      - task: install-dotnet-knoq
  
  install-dotnet-knoq:
    dir: ./libs
    cmds:
      - git clone https://github.com/YuHima03/dotnet-knoq.git
      - dotnet build dotnet-knoq/DotnetKnoq.sln -o dotnet-knoq/bin -f net9.0 -c Release

  tailwind-gen:
    dir: ./src/Dakoq.WebApp/Dakoq.WebApp
    cmds:
      - npx @tailwindcss/cli -i "./Styles/app.css" -o "./wwwroot/css/app.css"

  tailwind-watch:
    dir: ./src/Dakoq.WebApp/Dakoq.WebApp
    cmds:
      - npx @tailwindcss/cli -i "./Styles/app.css" -o "./wwwroot/css/app.css" --watch

  dev-up:
    cmds:
      - task: tailwind-gen
      - docker compose up -d --build

  dev-down:
    cmds:
      - docker compose down

  dev-restart:
    cmds:
      - task: tailwind-gen
      - docker compose build
      - docker compose down
      - docker compose up -d
